config/routes.rb
Rails.application.routes.draw do
  root 'users#login'
  resources :users do
    member do
      get 'question'
      get 'result'
    end
    collection do
      get 'login'
    end
  end

  get '/update_question' => 'users#update_question'
  get '/auth/:provider/callback' => 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
#引数に関連するユーザーが存在すればそれを返し、存在しまければ新規に作成する
  def self.find_or_create_from_auth_hash(auth_hash)
#OmniAuthで取得した各データを代入していく
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:name]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = nickname
      user.image_url = image_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def user_logged_in?
    if $session[:uid]
      begin
        @current_user = User.find_by(uid: $session[:uid])
      rescue ActiveRecord::RecordNotFound
        reset_user_session
      end
    end
    return if @current_user
    # @current_userが取得できなかった場合はログイン画面にリダイレクト
    flash[:referer] = request.fullpath
    redirect_to login_users_url
  end
  
  def reset_user_session
    $session[:uid] = nil
    @current_user = nil
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
# request.env['omniauth.auth']に、OmniAuthによってHashのようにユーザーのデータが格納されている。
    $session = User.find_by(uid: user.uid)


    redirect_to user_path($session)
  end


    
end

app/controllers/users_controller.rb
require 'csv'
class UsersController < ApplicationController
  before_action :set_user, only: [:result, :show, :edit, :update, :destroy, :question]
  before_action :user_logged_in?, except: [:show, :login]
  before_action :check_user, only: [:result, :edit, :update, :destroy, :question]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
  end

  def question
  end

  def login
    $session["uid"] = 0;
  end

  def result
    @recommend_jobs = calculate_distance(@user)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_question
    @user = User.find_by(id: params[:uid])
    @user.attributes = { params[:qid] => params[:ans] }
    @user.save()
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def check_user
      if $session.present?
        if @user.uid == $session.uid
        else
          redirect_to user_path($session)
        end
      else
        redirect_to login_user_path
      end
    end
      
    def set_user
      @user = User.find(params[:id])
    end

    def calculate_distance(user)
      csv_data = CSV.read('app/assets/data/jobs.csv', headers:false)
      jobs = {}
      response = []
      for data in csv_data do
        sum = 0
        if data[0] == "job_name" then
          next
        end
        for number in 1..5 do
          sum += (user["question" + number.to_s ].to_i - data[number].to_i) ** 2
        end
        jobs[data[0]] = sum
      end
      return jobs.sort_by{|k,v| v}
      for job in jobs.sort_by {|k, v| v} 
        response.append(job[0])
      end
      return response
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:provider, :uid, :name, :image_url, :old, :university, :job1, :job2, :job3, :question1, :question2, :question3, :question4, :question5)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackerwars</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=480">
  </head>

  <body>
    <header class="header">
      <img class="header__top-icon-image" src="/assets/logo_mini.png">
      <% if $session.present? then %>
        <% if $session.uid != "0" then %>
          <%= link_to 'Virtual Menter', user_path($session), class:"header__link-to-top" %>
        <% else %>
          <p class="header__link-to-top">Virtual Menter</p>
        <% end %>
      <% else %>
        <p class="header__link-to-top">Virtual Menter</p>
      <% end %>
      <% if $session.present? then %>
        <% if $session.uid != "0" then %>
          <%= link_to 'ログアウト', login_users_url(@user), class:"header__link-to-login" %>
        <% else %>
          <p class="header__link-to-login"></p>
        <% end %>
      <% end %>
    </header>
  
    <div class="container">
      <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="user">
  <div class="user-header-container">
    <p class="user-header-container__title">プロフィールを編集</p>
    <%= $session.uid %>
    user
    <%= @user.id %>
  </div>
  <div class="user-edit">
    <div class="user-edit__field">
      <%= form.label :name, class:"user-edit__filed__label" %>
      <br>
      <%= form.text_field :name, id: :user_name ,classs:"user-edit__filed__text"%>
    </div>

    <div class="user-edit__field">
      <%= form.label :old %>
      <br>
      <%= form.number_field :old, id: :user_old %>
    </div>

    <div class="user-edit__field">
      <%= form.label :university %>
      <br>
      <%= form.text_field :university, id: :user_university %>
    </div>

    <div class="user-edit__field">
      <%= form.label :job1 %>
      <br>
      <%= form.text_field :job1, id: :user_job1 %>
    </div>

    <div class="user-edit__field">
      <%= form.label :job2 %>
      <br>
      <%= form.text_field :job2, id: :user_job2 %>
    </div>

    <div class="user-edit__field">
      <%= form.label :job3 %>
      <br>
      <%= form.text_field :job3, id: :user_job3 %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_jobDetail.html.erb
<div id="modal-container">
  <div class="modal-background">
    <div class="modal" id="one">
      <h2>CEO</h2>
      <h3>会社を経営するという仕事</h3>
      <div id="people">
        <h2 align="left">Story</h2>
        <div>
          <h2 align="left">　伊東　豊</h2>
          <%= image_tag("/assets/ceo1.jpg", size: "100") %>

          <p>
          私立開成高校、東京大学卒業後、日本IBMに入社。<br>
          ベンチャー企業の設立に携わり、マーケティング、ウェブ系プロモーションを主に担当した後、<br>
          スローガンを設立。
          </p>
          <%= link_to '詳細', users_path %>
        </div>
        <br>
        <div>
          <h2 align="left">　仲 暁子</h2>
          <%= image_tag("/assets/ceo2.jpg", size: "100") %>

          <p>
          京都大学経済学部卒業後、ゴールドマン・サックス証券に入社。<br>
          退職後、Facebook Japanに初期メンバーとして参画。2010年9月、現ウォンテッドリーを設立。
          </p>
          <%= link_to '詳細', users_path %>
        </div>
      </div>

      <br>

      <div id="event">
        <h2 align='left'>1歩踏み出す</h2>
        <div>
          <!-- <h4 align="left">　Reach Your Audience!　アントレプレナーシップに必要な言語スキルを磨くための、英語での特別ワークショップ</h4> -->
          <%= image_tag("/assets/event1.jpg", width: "350px") %>

          <p>
          Startup Hub Tokyo
⾔語学を活かした様々なアクティビティを通して、⼈前で創造⼒豊かに表現できるようなるための特別ワークショップです！ビジネスピッチなどに役⽴つ英語プレゼンテーションスキルを身につけることができます。
</p>
          <%= link_to '詳細', users_path %>
        </div>
      </div>
      <svg class="modal-svg" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" preserveAspectRatio="none">
  		  <rect x="0" y="0" fill="none" width="226" height="162" rx="3" ry="3"></rect>
  		</svg>
    </div>
  </div>
</div>

app/views/users/_questionForm.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <head>
    <%= hidden_field :user, :id %>
  </head>
  
  <body>
      <!-- start padding container -->
      <div class="wrap">
          <!-- start jtinder container -->
          <div id="tinderslide">
              <ul>
                  <li class="pane1" id='last'>
                      <div class="img"></div>
                      <div>大人数よりは少人数が好き</div>
                      <div class="like"></div>
                      <div class="dislike"></div>
                  </li>
                  <li class="pane2">
                      <div class="img"></div>
                      <div>人を喜ばせることが好きである</div>
                      <div class="like"></div>
                      <div class="dislike"></div>
                  </li>
                  <li class="pane3">
                      <div class="img"></div>
                      <div>とにかくお金が欲しい</div>
                      <div class="like"></div>
                      <div class="dislike"></div>
                  </li>
                  <li class="pane4">
                      <div class="img"></div>
                      <div>理性的か感性的かと言われれば理性的</div>
                      <div class="like"></div>
                      <div class="dislike"></div>
                  </li>
                  <li class="pane5">
                      <div class="img"></div>
                      <div>リスクがあっても挑戦してみたい</div>
                      <div class="like"></div>
                      <div class="dislike"></div>
                  </li>
              </ul>
          </div>
          <!-- end jtinder container -->
      </div>
      <!-- end padding container -->
  
      <!-- jTinder trigger by buttons  -->
      <div class="actions">
          <a href="#" class="dislike"><i></i></a>
          <a href="#" class="like"><i></i></a>
      </div>
  
      <!-- jTinder status text  -->
      <div id="status"></div>
  
      <!-- jQuery lib -->
      <%= javascript_include_tag "jTinder/jquery.min.js" %>
      <!-- transform2d lib -->
      <%= javascript_include_tag "jTinder/jquery.transform2d.js" %>
      <!-- jTinder lib -->
      <%= javascript_include_tag "jTinder/jquery.jTinder.js" %>
      <!-- jTinder initialization script -->
      <%= javascript_include_tag "jTinder/main.js" %>
  </body>

  <!-- <div class="field"> -->
  <!--   <%= form.label :question1 %> -->
  <!--   <%= form.number_field :question1, id: :user_question1 %> -->
  <!-- </div> -->
  <!--  -->
  <!-- <div class="field"> -->
  <!--   <%= form.label :question2 %> -->
  <!--   <%= form.number_field :question2, id: :user_question2 %> -->
  <!-- </div> -->
  <!--  -->
  <!-- <div class="field"> -->
  <!--   <%= form.label :question3 %> -->
  <!--   <%= form.number_field :question3, id: :user_question3 %> -->
  <!-- </div> -->
  <!--  -->
  <!-- <div class="field"> -->
  <!--   <%= form.label :question4 %> -->
  <!--   <%= form.number_field :question4, id: :user_question4 %> -->
  <!-- </div> -->
  <!--  -->
  <!-- <div class="field"> -->
  <!--   <%= form.label :question5 %> -->
  <!--   <%= form.number_field :question5, id: :user_question5 %> -->
  <!-- </div> -->
  <!--  -->
  <!-- <div class="actions"> -->
  <!--   <%= form.submit %> -->
  <!-- </div> -->
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Old</th>
      <th>University</th>
      <th>Job1</th>
      <th>Job2</th>
      <th>Job3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @users.present? %>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.old %></td>
          <td><%= user.university %></td>
          <td><%= user.job1 %></td>
          <td><%= user.job2 %></td>
          <td><%= user.job3 %></td>
          <td><%= user.question1%></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div class="user">
  <div class="user-login">
    <img class="user-login__logo", src="/assets/logo.png">
    <%= link_to image_tag('/assets/twitter_login.png', {:width => '60%'}), '/auth/twitter', class:"user-login__image" %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/question.html.erb
<%= render 'questionForm', user:@user %>

<div class="user-links">
<%= link_to '途中結果を見る', result_user_path($session), class:"user-links__question" %>
</div>

app/views/users/result.html.erb
<%= stylesheet_link_tag "result", :media => "all" %>
<body>
  <div class="user-header-container">
    <div class="user-header-container__title">
    <p>診断結果</p>
    </div>
    <div class="user-header-detail2">
    <p>あなたにマッチしていそうな職種一覧です。<br>参考にしてください。</p>
    </div>
  </div>
  <%= render 'jobDetail' %>
  
  <div class="content">
    <div class="buttons">
    <% @recommend_jobs.first(8).each do |job| %>
      <div id="one" class="button">
        <h2>
          <%= job[0] %>
        </h2>
      </div>
    <% end %>
    </div>
  </div>
  <%= javascript_include_tag "result/main.js" %>
</body>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="user">
  <% if $session.present? then %>
    <% if $session.uid == @user.uid then %>
      <div class="user-edit-link-wrapper">
        <%= link_to 'プロフィールを変更する', edit_user_path(@user), class:"user-edit-link" %> 
      </div>
    <% end %>
  <% end %>
  <ul class="user-header-container">
    <li class="user-header-box">
      <div class="user-icon-wrapper">
        <% if @user.image_url.present? then %>
          <%= image_tag @user.image_url, class:"user-icon" %>
        <% else %>
          <img src=http://format.fideli.com/format/capture/1/4/10001.jpg class="user-icon" >
        <% end %>
      </div>

    </li>
    <li class="user-header-box">
      <div class="user-header-detail">
        <%= @user.name %>
      </div>
      <div class="user-header-detail">
        <p>年齢:
        <%= @user.old %>
        </p>
      </div>
    </li>
  </ul>

  <% if $session.present? then %>
    <% if $session.uid == @user.uid then %>
      <div class="user-links">
        <%= link_to 'ご教授を賜る', question_user_path(@user), class:"user-links__question" %> 
        <%= link_to '結果を見る', result_user_path(@user), class:"user-links__result" %> 
      </div>
    <% end %>
  <% end %>

  <div class="user-content-wrapper">
    <div class="user-content-title">
      <p>現在の仕事</p>
    </div>
    <div class="user-content-detail">
      <%= @user.job1 %>
    </div>
  </div>

  <div class="user-content-wrapper">
    <div class="user-content-title">
      <p>職歴</p>
    </div>
    <div class="user-content-detail">
      <%= @user.job1 %>
    </div>
    <div class="user-content-detail">
      <%= @user.job2 %>
    </div>
    <div class="user-content-detail">
      <%= @user.job3 %>
    </div>
  </div>
  <div class="user-content-wrapper">
    <div class="user-content-title">
      <p>学歴</p>
    </div>
    <div class="user-content-detail">
      <%= @user.university %>
    </div>
  </div>
</div>